title: comuunn
description: "um caderno aberto na internet"
baseurl: ""
permalink: /diario/:title/
markdown: kramdown

# pastas e arquivos que o Jekyll deve ignorar ao publicar
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
