title: comuunn 
tagline: "um caderno aberto na internet" 
description: | 
  This is a space for me to observe the subline of daily life. When I was younger, naturally life hit my heart through the eyes and I wrote down to, somehow, keep that fleeting image registred. With adulthood this sensibility was lost. And I never stoped being an f* adult. 

  Writing these code lines is my try to restore the mediocre artistic sensibility I once had. So, some facts about me. I'm a 27 years old English as a second language teacher, turning 28 this year and some days ago I decided that is not time enyomre to delay this weird unamed desire to write.

  Here you'll find a collection of my days and some atempts to catch images and montages of events in my routine that I find interesting but didn't have - until now - a place to place them. Like a gallery of what I find interesting. That includes bugs just living, fun lights and shadows, angles, colors, textures, people, situations and so many other things.

  My hope is to create a space where I can share my thoughts and feelings about the world around me, and maybe even connect with others who can see the subtil beauty of mere trifles.


baseurl: ""
permalink: /diario/:title/
markdown: kramdown

# pastas e arquivos que o Jekyll deve ignorar ao publicar
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
