title: comuunn 
tagline: "um caderno aberto na internet" 
description: "|aqui você escreve o texto grande que vai aparecer só na seção about this, |pode ser bem mais longo que isso, |quantas frases você quiser."
baseurl: ""
permalink: /diario/:title/
markdown: kramdown

# pastas e arquivos que o Jekyll deve ignorar ao publicar
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
